---
title: "Differential expression analysis--DEseq2 standard"
author: "Siming Zhao"
date: "December 2, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE)
```

Load data
```{r loaddata}
source("code/summary_functions.R")
library(dplyr)
load("data/DE_input.Rd")
glocus <- "VPS45"
dim(dm)[1]
gcount <- dm[1:(dim(dm)[1]-76), colnames(dm1dfagg)[dm1dfagg[glocus,] >0 & nlocus==1]]
# negative control cells defined as neg gRNA targeted cells
ncount <- dm[1:(dim(dm)[1]-76), colnames(dm1dfagg)[dm1dfagg["neg",] >0 & nlocus==1]]
coldata <- data.frame(row.names = c(colnames(gcount),colnames(ncount)),     
                      condition=c(rep('G',dim(gcount)[2]),rep('N',dim(ncount)[2])))
countall <- cbind(gcount,ncount)
totalcount <- apply(countall,1,sum)
cellpercent <-  apply(countall,1,function(x) length(x[x>0])/length(x))
```

run deseq2 standard function
```{r deseq2func}
library(DESeq2)
run_deseq2 <- function(dds) {
  dds = estimateSizeFactors(dds)
  ddsWARD = DESeq(dds)
  resWARD = results(ddsWARD)
  summ_pvalues(resWARD$pvalue[!is.na(resWARD$pvalue)])
  resSigWARD <- subset(resWARD, padj < 0.1)
  print(paste0("There are ",dim(resSigWARD)[1], " genes passed FDR <0.1 cutoff"))
  print(knitr::kable(signif(as.matrix(head(resWARD[order(resWARD$pvalue),])),digit=2)))
  return(resWARD)
}
```

## Run DEseq2--No filtering
```{r deseq2}
dds = DESeqDataSetFromMatrix(countData = countall, colData = coldata,design = ~condition)
res <- run_deseq2(dds)
```
## Run DEseq2--at least one cell UMI > 0 
```{r deseq2>0}
dds = DESeqDataSetFromMatrix(countData = countall[totalcount>0,], colData = coldata,design = ~condition)
res <- run_deseq2(dds)
```
## Run DEseq2--3% cells with UMI > 0
```{r deseq20.03}
dds = DESeqDataSetFromMatrix(countData = countall[cellpercent > 0.03,], colData = coldata,design = ~condition)
res <- run_deseq2(dds)
```
## Run DEseq2--10% cells with UMI > 0
```{r deseq20.1}
dds = DESeqDataSetFromMatrix(countData = countall[cellpercent > 0.1,], colData = coldata,design = ~condition)
res <- run_deseq2(dds)
```
## Run DEseq2--20% cells with UMI > 0
```{r deseq20.2}
dds = DESeqDataSetFromMatrix(countData = countall[cellpercent > 0.2,], colData = coldata,design = ~condition)
res <- run_deseq2(dds)
```

## Parameters used
* We used data processed after QC step [here](Quality_metrics.html).  
* targeted locus, choose `r glocus`. 
