---
title: "gRNA resEdgeR_QLF result"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
This summarizes results obtained from running `module load R; Rscript code/gRNA_edgeR-QLF_run.R` from shell.

```{r}
library(Matrix)
load("data/DE_input.Rd")
source("code/qq-plot.R")
gRNAdm0 <- dm[(dim(dm)[1]-75):dim(dm)[1],]
```
## Using only cells with negative control gRNA as controls
```{r, message=F}
source("code/empiricalFDR.R")

pbins <- 10** (-4:-10)
for (gRNAfile in  list.files("data/gRNA_edgeR-QLF/", "*edgeR-qlf_Neg1.Rd")){
  print(gRNAfile)
  gRNA <- strsplit(gRNAfile, "_edgeR")[[1]][1]
  gRNAlocus <- strsplit(gRNA, split = "_")[[1]][1]
  load(paste0("data/gRNA_edgeR-QLF/", gRNAfile))
  
  # fdrmetricall <- empiricalFDR(res1$table$PValue, res1$table$PValue, unlist(lapply(permres1, function(x) x$table$PValue)))
  # empiricalPall <- empiricalPvalue(res1$table$PValue, unlist(lapply(permres1, function(x) x$table$PValue)))
  # empiricalPfdrall <- p.adjust(empiricalPall, method="BH")
  # resEmpiricalp <- cbind(res1$table, fdrmetricall,empiricalPall,empiricalPfdrall)
  # save(resEmpiricalp, file=paste0("data/gRNA_edgeR-QLF/", gRNA,"_edgeR-qlf_Neg1_Empricialp.Rd"))
  load(paste0("data/gRNA_edgeR-QLF/", gRNA,"_edgeR-qlf_Neg1_Empricialp.Rd"))
  fdrmetrical <-  resEmpiricalp[,6:8]
  empiricalPall <-  resEmpiricalp[,9]
  empiricalPfdrall <-  resEmpiricalp[,10]
  
  outpvalues <- c(res1$table[1:10,"PValue"], pbins)
  outpbins <- matrix(NA, nrow=length(pbins), ncol=dim(res1$table)[2])
  rownames(outpbins) <- pbins
  colnames(outpbins) <- colnames(res1$table)
  outm <- rbind(res1$table[1:10,], outpbins)
  fdrmetric <- empiricalFDR(outpvalues, res1$table$PValue, unlist(lapply(permres1, function(x) x$table$PValue)))
  empiricalP <- c(empiricalPall[1:10], rep(NA,length(pbins)))
  empiricalP.FDR <- c(empiricalPfdrall[1:10], rep(NA,length(pbins)))
  outm <- cbind(outm,empiricalP,empiricalP.FDR, fdrmetric)
  print(signif(outm,2))
  plotgn <- rownames(outm[1:10,][outm[1:10, "EmpiricalFDR"] <0.2,])
  if (length(plotgn)!=0){
    for (gn in plotgn){
      gcount <- dm[gn, gRNAdm0[gRNA,] >0 & colSums(gRNAdm0[rownames(gRNAdm0) != gRNA,]) == 0]
      ncount1 <- dm[gn, colnames(dm1dfagg)[dm1dfagg["neg",] >0 & nlocus==1]]
      a <- rbind(cbind(gcount,1),cbind(ncount1,2))
      colnames(a) <- c("count","categ")
      par(mfrow=c(1,3))
      boxplot(count ~categ, data = a, lwd = 2, main=paste(gRNA, gn, sep=":"),  outcol="white")
      stripchart(count ~categ, data=a, vertical = TRUE,  method = "jitter", add = TRUE, pch = 21, cex=2, col = 'blue')
      qqplot( -log10(unlist(lapply(permres1, function(x) x$table$PValue))),-log10(res1$table$PValue), xlab="permuted (-log10 pvalue)", ylab="observed (-log10 pvalue)")
      abline(a=0, b=1, col="red")
      grid()
      qqplot(-log10(runif(length(empiricalPall))),-log10(empiricalPall))
      abline(a=0, b=1, col="red")
      grid()
    }
  }
}
```
## Using all cells except the ones with targeted gRNA as controls

```{r, message=F, eval=F}
source("code/empiricalFDR.R")

pbins <- 10** (-4:-10)
for (gRNAfile in  list.files("data/gRNA_edgeR-QLF/", "*edgeR-qlf_Neg2.Rd")){
  print(gRNAfile)
  gRNA <- strsplit(gRNAfile, "_edgeR")[[1]][1]
  gRNAlocus <- strsplit(gRNA, split = "_")[[1]][1]
  load(paste0("data/gRNA_edgeR-QLF/", gRNAfile))
  
  # fdrmetricall <- empiricalFDR(res2$table$PValue, res2$table$PValue, unlist(lapply(permres2, function(x) x$table$PValue)))
  # empiricalPall <- empiricalPvalue(res2$table$PValue, unlist(lapply(permres2, function(x) x$table$PValue)))
  # empiricalPfdrall <- p.adjust(empiricalPall, method="BH")
  # resEmpiricalp <- cbind(res2$table, fdrmetricall,empiricalPall,empiricalPfdrall)
  # save(resEmpiricalp, file=paste0("data/gRNA_edgeR-QLF/", gRNA,"_edgeR-qlf_Neg2_Empricialp.Rd"))
  
  load(paste0("data/gRNA_edgeR-QLF/", gRNA,"_edgeR-qlf_Neg2_Empricialp.Rd"))
  fdrmetrical <-  resEmpiricalp[,6:8]
  empiricalPall <-  resEmpiricalp[,9]
  empiricalPfdrall <-  resEmpiricalp[,10]
  
  outpvalues <- c(res2$table[1:10,"PValue"], pbins)
  outpbins <- matrix(NA, nrow=length(pbins), ncol=dim(res2$table)[2])
  rownames(outpbins) <- pbins
  colnames(outpbins) <- colnames(res2$table)
  outm <- rbind(res2$table[1:10,], outpbins)
  fdrmetric <- empiricalFDR(outpvalues, res2$table$PValue, unlist(lapply(permres2, function(x) x$table$PValue)))
  empiricalP <- c(empiricalPall[1:10], rep(NA,length(pbins)))
  empiricalP.FDR <- c(empiricalPfdrall[1:10], rep(NA,length(pbins)))
  outm <- cbind(outm,empiricalP,empiricalP.FDR, fdrmetric)
  print(signif(outm,2))
  plotgn <- rownames(outm[1:10,][outm[1:10, "EmpiricalFDR"] <0.2,])
  if (length(plotgn)!=0){
    for (gn in plotgn){
      gcount <- dm[gn, gRNAdm0[gRNA,] >0 & colSums(gRNAdm0[rownames(gRNAdm0) != gRNA,]) == 0]
      ncount2 <- dm[gn, colnames(dm1dfagg)[dm1dfagg[gRNAlocus,] == 0]]
      a <- rbind(cbind(gcount,1),cbind(ncount2,2))
      colnames(a) <- c("count","categ")
      par(mfrow=c(1,3))
      boxplot(count ~categ, data = a, lwd = 2, main=paste(gRNA, gn, sep=":"),  outcol="white")
      stripchart(count ~categ, data=a, vertical = TRUE,  method = "jitter", add = TRUE, pch = 21, cex=2, col = 'blue')
      qqplot( -log10(unlist(lapply(permres2, function(x) x$table$PValue))),-log10(res2$table$PValue), xlab="permuted (-log10 pvalue)", ylab="observed (-log10 pvalue)")
      abline(a=0, b=1, col="red")
      grid()
      qqplot(-log10(runif(length(empiricalPall))),-log10(empiricalPall))
      abline(a=0, b=1, col="red")
      grid()
    }
  }
}
```
